functionality:
  name: base_pytorch_nvidia
  description: An nvcr.io pytorch 24.03-py3 with anndata preinstalled.
platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:24.03-py3
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - anndata~=0.8.0
          - scanpy
          - pyyaml
          - requests
          - jsonschema
