functionality:
  name: base_pytorch_cuda
  description: An nvcr.io pytorch 22.12 with anndata preinstalled.
platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:22.12-py3
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - anndata~=0.8.0
          - scanpy
          - pyyaml
          - requests
          - jsonschema
