name: Base images for openproblems v2

on:
  schedule:
    - cron: '00 22 * * 6'


jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - { image: 'base-image-python', version: 'v1',  extra_tags: '' }
          - { image: 'base-image-r', version: 'v1', extra_tags: ''}
          - { image: 'base-image-bioc', version: 'v1', extra_tags: '' }
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GTHB_PAT }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: GITHUB_PAT=${{ secrets.PAT }}
          tags: ghcr.io/openproblems-bio/${{ matrix.config.image }}:${{ matrix.config.version }}${{ matrix.config.extra_tags }}
          file: ${{ matrix.config.image }}/${{ matrix.config.version }}.Dockerfile
          push: true